// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: unity_basic_env.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Unitybasicenv {

  /// <summary>Holder for reflection information generated from unity_basic_env.proto</summary>
  public static partial class UnityBasicEnvReflection {

    #region Descriptor
    /// <summary>File descriptor for unity_basic_env.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityBasicEnvReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV1bml0eV9iYXNpY19lbnYucHJvdG8SDXVuaXR5YmFzaWNlbnYiVQoRVW5p",
            "dHlCYXNpY0Vudk5vdGUSDwoHbWVzc2FnZRgBIAEoCRIRCglhY3Rpb25PYnMY",
            "AiABKAUSDgoGcmV3YXJkGAMgASgCEgwKBGRvbmUYBCABKAgybgoNVW5pdHlC",
            "YXNpY0VudhJdChFVbml0eUJhc2ljRW52Q2hhdBIgLnVuaXR5YmFzaWNlbnYu",
            "VW5pdHlCYXNpY0Vudk5vdGUaIC51bml0eWJhc2ljZW52LlVuaXR5QmFzaWNF",
            "bnZOb3RlIgAoATABQjsKHWlvLmdycGMuZXhhbXBsZXMudW5pdGJhc2ljZW52",
            "QhJVbml0eUJhc2ljRW52UHJvdG9QAaICA1VCRWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Unitybasicenv.UnityBasicEnvNote), global::Unitybasicenv.UnityBasicEnvNote.Parser, new[]{ "Message", "ActionObs", "Reward", "Done" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A UnityBasicEnvNote is a message sent while at a given point.
  /// </summary>
  public sealed partial class UnityBasicEnvNote : pb::IMessage<UnityBasicEnvNote> {
    private static readonly pb::MessageParser<UnityBasicEnvNote> _parser = new pb::MessageParser<UnityBasicEnvNote>(() => new UnityBasicEnvNote());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityBasicEnvNote> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Unitybasicenv.UnityBasicEnvReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityBasicEnvNote() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityBasicEnvNote(UnityBasicEnvNote other) : this() {
      message_ = other.message_;
      actionObs_ = other.actionObs_;
      reward_ = other.reward_;
      done_ = other.done_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityBasicEnvNote Clone() {
      return new UnityBasicEnvNote(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    /// <summary>
    /// The message to be sent.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "actionObs" field.</summary>
    public const int ActionObsFieldNumber = 2;
    private int actionObs_;
    /// <summary>
    ///when coming from client to server its an action
    ///when coming from server to client its an obs (spot where the unit is)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ActionObs {
      get { return actionObs_; }
      set {
        actionObs_ = value;
      }
    }

    /// <summary>Field number for the "reward" field.</summary>
    public const int RewardFieldNumber = 3;
    private float reward_;
    /// <summary>
    ///reward from the env (generated by server)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Reward {
      get { return reward_; }
      set {
        reward_ = value;
      }
    }

    /// <summary>Field number for the "done" field.</summary>
    public const int DoneFieldNumber = 4;
    private bool done_;
    /// <summary>
    ///true if env episode is done (generated by server)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Done {
      get { return done_; }
      set {
        done_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityBasicEnvNote);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityBasicEnvNote other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (ActionObs != other.ActionObs) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Reward, other.Reward)) return false;
      if (Done != other.Done) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (ActionObs != 0) hash ^= ActionObs.GetHashCode();
      if (Reward != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Reward);
      if (Done != false) hash ^= Done.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (ActionObs != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ActionObs);
      }
      if (Reward != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Reward);
      }
      if (Done != false) {
        output.WriteRawTag(32);
        output.WriteBool(Done);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (ActionObs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ActionObs);
      }
      if (Reward != 0F) {
        size += 1 + 4;
      }
      if (Done != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityBasicEnvNote other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.ActionObs != 0) {
        ActionObs = other.ActionObs;
      }
      if (other.Reward != 0F) {
        Reward = other.Reward;
      }
      if (other.Done != false) {
        Done = other.Done;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 16: {
            ActionObs = input.ReadInt32();
            break;
          }
          case 29: {
            Reward = input.ReadFloat();
            break;
          }
          case 32: {
            Done = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
